### ISSUE TITLE
Generate model does not generate anything.

### ISSUE THREAD

**Issue by arjenmeijer** [mootensai/yii2-enhanced-gii#7]
Generating code using template "/var/www/html/profiel.3de5.nl/vendor/mootensai/yii2-enhanced-gii/model/default"...
skipped models/base/app/models/Vergelijkprofielen.php
skipped models/app/models/Vergelijkprofielen.php
skipped models/app/models/VergelijkprofielenQuery.php
done!

So the message is: generated successful, but I do not know why it skipped the models. The path looks very strange: models/apps/models? The original input is only the class name. Not model/base/app/models
Something strange is going on.

**Comment by mootensai** [comment]
Thanks! It should be fixed by now..

**Comment by arjenmeijer** [comment]
this is entered in model class even if I input Vergelijkprofielen:
app\models\TblVergelijkprofielen

I do not need app\models\Tbl.

**Comment by mootensai** [comment]
maybe you checked 'use table prefix' ?

**Comment by karneaud** [comment]
I installed via composer the yii2 advanced template with your enhanced gii and still get the Models not being generated issue. What was the fix? a
